version: '3.8'

services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "bash prestart.sh && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8006:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./db/.env

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/:/usr/src/app

  beatport:
    build:
      context: ./beatport
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./beatport/.env
    ports:
      - "8066:8000"

  spotify:
    build:
      context: ./spotify
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./spotify/.env
    ports:
      - "8067:8000"