version: '3.8'

services:
  quiz-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "bash prestart.sh && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8007:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - ./backend/.env
    depends_on:
      - quiz-db

  quiz-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
