"""add beatport artist

Revision ID: 164e8b5d0137
Revises: 40f9d1dfd851
Create Date: 2022-10-30 05:16:53.649921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '164e8b5d0137'
down_revision = '40f9d1dfd851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
