"""change bp session name

Revision ID: 2155f653f4b6
Revises: 4dd037cabf2c
Create Date: 2022-12-28 17:54:47.953945

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2155f653f4b6'
down_revision = '4dd037cabf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bpsession',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('sheet_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Date(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sheet_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], name='session_pack_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.drop_table('bpsession')
    # ### end Alembic commands ###
