"""add id to pack model

Revision ID: 2a43b6843b53
Revises: 4cb3629c3567
Create Date: 2022-10-23 16:04:16.550515

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2a43b6843b53'
down_revision = '4cb3629c3567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'pack', ['style_id', 'period_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pack', type_='unique')
    op.drop_column('pack', 'id')
    # ### end Alembic commands ###
