"""remove period name constraint

Revision ID: 2d0856cdccbe
Revises: 9d988aaa1785
Create Date: 2022-11-07 20:50:14.017533

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d0856cdccbe'
down_revision = '9d988aaa1785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_period_name', table_name='period')
    op.create_index(op.f('ix_period_name'), 'period', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_name'), table_name='period')
    op.create_index('ix_period_name', 'period', ['name'], unique=False)
    # ### end Alembic commands ###
