"""change unique constraint for styles

Revision ID: 2de84a0fe626
Revises: 49229117b843
Create Date: 2022-10-16 11:04:28.059439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2de84a0fe626'
down_revision = '49229117b843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_style_name', table_name='style')
    op.create_index(op.f('ix_style_name'), 'style', ['name'], unique=False)
    op.create_unique_constraint(None, 'style', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'style', type_='unique')
    op.drop_index(op.f('ix_style_name'), table_name='style')
    op.create_index('ix_style_name', 'style', ['name'], unique=False)
    # ### end Alembic commands ###
