"""add beatport label id uniq

Revision ID: 40f9d1dfd851
Revises: befebb73549a
Create Date: 2022-10-26 06:27:16.043058

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40f9d1dfd851'
down_revision = 'befebb73549a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_label_bp_id', table_name='label')
    op.create_index(op.f('ix_label_bp_id'), 'label', ['bp_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_bp_id'), table_name='label')
    op.create_index('ix_label_bp_id', 'label', ['bp_id'], unique=False)
    # ### end Alembic commands ###
