"""add pack releas link

Revision ID: 83942bd985ee
Revises: 2d0856cdccbe
Create Date: 2022-11-20 18:19:39.942504

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '83942bd985ee'
down_revision = '2d0856cdccbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packrelease',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('audited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'release_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packrelease')
    # ### end Alembic commands ###
