"""add beatport release

Revision ID: 9247230db5d7
Revises: b9e16ac96467
Create Date: 2022-10-30 16:53:31.265954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9247230db5d7'
down_revision = 'b9e16ac96467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bp_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_bp_id'), 'release', ['bp_id'], unique=True)
    op.create_index(op.f('ix_release_name'), 'release', ['name'], unique=False)
    op.create_table('releaseartist',
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releaseartist')
    op.drop_index(op.f('ix_release_name'), table_name='release')
    op.drop_index(op.f('ix_release_bp_id'), table_name='release')
    op.drop_table('release')
    # ### end Alembic commands ###
