"""add beatport release relations

Revision ID: 9d988aaa1785
Revises: 9247230db5d7
Create Date: 2022-10-30 19:16:11.235390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9d988aaa1785'
down_revision = '9247230db5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
