"""add beatport artist

Revision ID: b9e16ac96467
Revises: 40f9d1dfd851
Create Date: 2022-10-30 05:39:20.327164

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b9e16ac96467'
down_revision = '40f9d1dfd851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bp_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_bp_id'), 'artist', ['bp_id'], unique=True)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_index(op.f('ix_artist_bp_id'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
