"""move audited into release

Revision ID: c4d97810d638
Revises: 2155f653f4b6
Create Date: 2023-07-23 09:33:02.925242

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4d97810d638'
down_revision = '2155f653f4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packrelease', 'audited')
    op.add_column('release', sa.Column('audited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'audited')
    op.add_column('packrelease', sa.Column('audited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
